EMAIL_TIME_OUT_MSG = 'We are experiencing an issue on one of our service, please try again after few minutes.'
EMAIL_NOT_DELIVERABLE_ERR_MSG = 'Invalid email! email address is not deliverable.'
INACTIVE_USER_ERR_MSG = 'Cannot log in as inactive user.'
LOGIN_CRED_ERR_MSG = 'Unable to log in with provided credentials.'
INVALID_EXISTING_PASSWORD_ERR_MSG = 'Invalid existing password.'
