# Generated by Django 4.0.1 on 2022-01-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('city', models.CharField(blank=True, max_length=48, null=True)),
                ('region', models.CharField(blank=True, max_length=48, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('timezone', models.CharField(blank=True, max_length=32, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=8, null=True)),
                ('joined_day_holiday', models.CharField(blank=True, max_length=32, null=True, verbose_name="Name of the holiday on user's joined day")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
